Develop3
4e27c1/Diplom3 pull request #1
Opened 2023-11-02 14:50 UTC by 4e27c1

2023-11-04 20:48 UTC, pavel-ulan requested changes
Тут уже было где развернуться, если так можно сказать =)
Есть что реализовано клево. И большинство тестов требуют только косметических исправлений. Однако есть и те, которые работают совершенно не так как требуется. Так же есть ряд спорных решений по утилитным классам. Посмотри комменты и жду твоих исправлений.

2023-11-04 20:48 UTC, pavel-ulan commented on src/main/java/praktikum/pages/Environment.java
> +    public static final String YANDEX_DRIVER = System.getProperty("webdriver.chrome.driver", "src/main/resources/chromedriver114.exe");
**можно лучше**
хорошо, что использовала относительный путь, но где же сам драйвер? почему не добавила к репозиторию (как правило resources в таком случае тоже добавляют в git репозиторий)

2023-11-04 20:48 UTC, pavel-ulan commented on src/main/java/praktikum/pages/Environment.java
> +    public static final String YANDEX_BINARY = System.getProperty("webdriver.yandex.binary", "C:\\Program Files\\Yandex\\YandexBrowser\\Application\\browser.exe");
**надо исправить**
ну а вот это уже промах =)
никогда не используй абсолютный путь, да еще и с привязкой к ОС. большинство систем крутятся на unix based ОС (просто загугли сколько в doker hub контейнеров с win OC и Unix OC), для которых структура каталогов вообще не такая. Т.е. твой код изначально не будет работать по причине отсутствия такого пути.

2023-11-04 20:48 UTC, pavel-ulan commented on src/main/java/praktikum/pages/LKPage.java
> +    public static final By PROFILE = By.xpath("//*[@id=\"root\"]/div/main/div/nav/ul/li[1]/a");
**надо исправить**
Старайся не использовать локаторы состоящие только из пути (не важно относительный/абсолютный). Как правило всегда можно подобрать другой, более читаемый, локатор. Такие локаторы плохо читаются, по ним непонятно, куда они указывают и если что-то меняется в верстке, то они ломаются и могут или никуда не вести или, что еще хуже, возвращать совершенно другой элемент. 
привязка к @id=\"root\" в данном случае почти ни на что не повлияет

2023-11-04 20:48 UTC, pavel-ulan commented on src/test/java/praktikum/ConstructorTest.java
> +        Assert.assertTrue(mainPage.checkScrollingToFirstPositions(mainPage.getFirstFillingLocator()));
**надо исправить**
ммм.... задание звучало как  "Проверь, что работают переходы к разделам". в твоем исполнении я вижу, что мы проверяем картинку на присутствие. Скажем так, проверка невалидная.
ты не проверяешь сработал ли переход по разделам.
Попробуй проскролить разделы и смотреть как меняются имена классов в верстке у разделов. И построй проверку "в каком разделе я нахожусь" на этой основе. тогда можно проверить, что после клика на нужный раздел, ты оказалась именно там.

2023-11-04 20:48 UTC, pavel-ulan commented on src/test/java/praktikum/DriverRule.java
**отлично**
круть, молодец. Для текущего задания реализация отличная

2023-11-04 20:48 UTC, pavel-ulan commented on src/test/java/praktikum/LKTest.java
> +        System.out.println(accessToken);
Ну, думаю уже понимаешь, что sout не лучшее решение =)

2023-11-04 20:48 UTC, pavel-ulan commented on src/test/java/praktikum/LKTest.java
> +                .fillRegisterForm(user.getName(), user.getEmail(), user.getPassword());
**надо исправить**
у тебя даже UserClient класс есть, где через API call можно создать необходимого пользователя. Почему ты используешь более нестабильный и медленный UI слой?

2023-11-04 20:48 UTC, pavel-ulan commented on src/test/java/praktikum/LKTest.java
> +        UserClient.delete(accessToken);
**отлично**
Ну, зато удаляешь правильно =)
И главное, что не забываешь это делать 👍

2023-11-04 20:48 UTC, pavel-ulan commented on src/main/java/praktikum/pages/RegisterPage.java
> +        regClick();
**надо исправить**
Я чуть дальше еще оставлю коммент, но у тебя есть API вызов для этого действия. Всегда смотри на тестируемый сервис шире и если у тебя проверка не заключается в проверке регистрации через форму, то для чего усложнять себе жизнь?
а еще этот метод даже не возвращает тебе статус, зарегистрировался user или нет.
в общем со всех сторон спорное решение. Особенно с учетом, что у тебя регистрация реализована в UserClient

2023-11-05 05:34 UTC, 4e27c1 commented on src/main/java/praktikum/pages/RegisterPage.java
> +        regClick();
Одно из заданий как раз проверка регистрации через форму, вот этот класс как раз подготавливает данные для этого действа. в остальном замечание поняла и в других тестовых классах исправила и рега происходит через UserClient.

2023-11-05 05:36 UTC, 4e27c1 commented on src/test/java/praktikum/ConstructorTest.java
> +        Assert.assertTrue(mainPage.checkScrollingToFirstPositions(mainPage.getFirstFillingLocator()));
Нам куратор на вебинаре так говорил делать и я так поняла, что это достаточная проверка)

2023-11-05 05:38 UTC, 4e27c1 commented on src/main/java/praktikum/pages/Environment.java
> +    public static final String YANDEX_BINARY = System.getProperty("webdriver.yandex.binary", "C:\\Program Files\\Yandex\\YandexBrowser\\Application\\browser.exe");
Хотелось бы больше подсказок, как это сделать, я сама понимаю, что не самая правильная реализация, но в спринте, где мы проходили данный кейс (только с ФФ), у меня приняли именно такую реализацию. ну и у других ребят с потока.
@pavel-ulan , подскажите, как исполняемый файл для винды сделать универсальным? я не оч представляю как сделать. я ж не могу его в ресурсы запихать?

2023-11-05 14:05 UTC, 4e27c1 commented on src/test/java/praktikum/LKTest.java
> +                .fillRegisterForm(user.getName(), user.getEmail(), user.getPassword());
убрала

2023-11-05 14:06 UTC, 4e27c1 commented on src/test/java/praktikum/LKTest.java
> +        System.out.println(accessToken);
пролез отладочный, убрала

2023-11-05 21:09 UTC, 4e27c1 commented on src/main/java/praktikum/pages/Environment.java
> +    public static final String YANDEX_DRIVER = System.getProperty("webdriver.chrome.driver", "src/main/resources/chromedriver114.exe");
Добавила драйвера в git репозиторий

2023-11-05 21:11 UTC, 4e27c1 commented on src/main/java/praktikum/pages/Environment.java
> +    public static final String YANDEX_BINARY = System.getProperty("webdriver.yandex.binary", "C:\\Program Files\\Yandex\\YandexBrowser\\Application\\browser.exe");
Убрала пути из Environment, добавила в Readme описание как запускать тесты и на локальной машине, и на любой другой.
Идеальным решением было бы вынести все это в докер со своими браузерами и универсальными путями, но это в рамках работы не требуется, поэтому, по согласованию с наставником, сделали такой вариант.

2023-11-05 21:12 UTC, 4e27c1 commented on src/main/java/praktikum/pages/LKPage.java
> +    public static final By PROFILE = By.xpath("//*[@id=\"root\"]/div/main/div/nav/ul/li[1]/a");
почистила локаторы. в одном месте подобрать "совсем красивый" не удалось, оставила просто красивый. в остальных вроде везде читаемые

2023-11-05 21:13 UTC, 4e27c1 commented on src/test/java/praktikum/ConstructorTest.java
> +        Assert.assertTrue(mainPage.checkScrollingToFirstPositions(mainPage.getFirstFillingLocator()));
добавила проверку на подсветку выбранного раздела, именно тут не самые красивые локаторы, но иначе никак, три абсолютно идентичных локатора для разделов, пришлось с путями заморочиться

2023-11-06 22:04 UTC, pavel-ulan approved these changes
Да, хорошо =)

2023-11-07 04:47 UTC, merged